/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#e1e3de",
        "secondary-dim": "#565955",
        "surface-container-highest": "#e7ebd0",
        "tertiary-fixed-dim": "#dee9d9",
        "on-primary-fixed-variant": "#50604c",
        surface: "#fefdf1",
        "primary-container": "#d6e8cf",
        "on-primary-container": "#465643",
        "on-surface": "#363a27",
        tertiary: "#5d675b",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#595c59",
        background: "#fefdf1",
        "on-surface-variant": "#626651",
        "surface-container-low": "#fafaeb",
        primary: "#53634f",
        "tertiary-container": "#ecf7e7",
        "primary-fixed": "#d6e8cf",
        "surface-variant": "#e7ebd0",
        outline: "#7f836c",
        secondary: "#626561",
        "primary-fixed-dim": "#c8dac1",
        "surface-dim": "#e1e5c7",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#3d403d",
        "on-primary": "#ebfde3",
        "on-error-container": "#742410",
        "secondary-fixed-dim": "#d3d5d0",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error-dim": "#5c1202",
        "inverse-primary": "#edffe5",
        "on-tertiary-container": "#545e53",
        "on-background": "#363a27",
        error: "#a54731",
        "on-tertiary-fixed": "#424c41",
        "surface-bright": "#fefdf1",
        "primary-dim": "#475744",
        "surface-container": "#f4f5e2",
        "error-container": "#fe8b70",
        "on-secondary-container": "#4f534f",
        "on-tertiary-fixed-variant": "#5f695d",
        "outline-variant": "#b8bca3",
        "inverse-surface": "#0d0f08",
        "inverse-on-surface": "#9d9d93",
        "tertiary-fixed": "#ecf7e7",
        "tertiary-dim": "#515b4f",
        "on-primary-fixed": "#344331",
        "surface-container-high": "#edf0d9",
        "surface-tint": "#53634f",
        "secondary-fixed": "#e1e3de",
        // Backward-compatible aliases already used by existing components.
        "background-light": "#fefdf1",
        "background-dark": "#0d0f08",
        "text-muted": "#626651",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        editorial: "0 12px 40px rgba(54, 58, 39, 0.06)",
      },
    },
  },
  plugins: [],
};
